@startuml
title Initialize game sequence diagram : initGame()

actor User as U
participant "<<static>>\nDungeonCrawlerUI" as UI
participant "DungeonCrawler" as DC
participant Player
participant Dungeon

DC -> UI : Call to prompt user to select class
UI -> U : Prompt user to select class
U -> UI : User selects class
UI -> DC : Pass user class choice
DC -> Player : Create Player based on user choice
activate Player
DC <-- Player : Return Player object
deactivate Player


DC -> UI : Call to prompt user to select dungeon
UI -> U : Prompt user to select dungeon
U -> UI : User selects dungeon
UI -> DC : Pass dungeon class choice
DC -> Player : Create Dungeon based on user choice
activate Player
DC <-- Player : Return Dungeon object
deactivate Player

DC -> Dungeon : Generate random Weapon
activate Dungeon
DC <-- Dungeon : Returns Weapon object
deactivate Dungeon
DC -> Player : Equip generated Weapon object
@enduml
